global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - Can add alerting configs like rules.yml"

scrape_configs:
  - job_name: 'sentiment-api'
    static_configs:
      - targets: ['sentiment-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s
